### ISSUE TITLE
virtual-audio-graph

### ISSUE THREAD

**Issue by benji6** [alemangui/web-audio-resources#1]
Hi, was wondering whether you would consider adding my library [virtual-audio-graph](https://github.com/benji6/virtual-audio-graph) to this list? It's currently featured on the Awesome WebAudio list. Thanks!

**Comment by alemangui** [comment]
Hey, I took a look at the library, it's very cool! I'd be happy to include it. Feel free to submit a PR

**Comment by benji6** [comment]
Thanks :) PR here #2
